export class Static {
  static readonly AUTO_GENERATED_COMMENT = "// This file is auto-generated by prismadoc. Do not edit manually." as const;

  static readonly DEFAULT_EXAMPLES = {
    cuid: "cmfxu4njg000008l52v7t8qze",
    datetime: "2025-09-03T03:00:00.000Z",
    int: 777,
    string: "ordinary string",
    fallback: "aaaa",
  } as const;
}
